name: Build Odyssey

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clean build directory
      run: |
        rm -rf build Payload Odyssey.ipa
        make -C amfidebilitate clean

    - name: Build amfidebilitate
      run: make -C amfidebilitate clean all

    - name: Extract and prepare base binaries
      run: |
        cd Odyssey/resources && tar -xf basebinaries.tar
        rm -f Odyssey/resources/{amfidebilitate,basebinaries.tar}
        cp amfidebilitate/bin/* Odyssey/resources

    - name: Create base binaries tarball
      run: |
        cd Odyssey/resources && tar -cf basebinaries.tar amfidebilitate jailbreakd jbexec launchjailbreak pspawn_payload-stg2.dylib pspawn_payload.dylib
        rm -f Odyssey/resources/{amfidebilitate,jailbreakd,jbexec,launchjailbreak,*.dylib}

    - name: Build Odyssey using Xcode
      run: |
        xcodebuild clean build CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO PRODUCT_BUNDLE_IDENTIFIER="org.coolstar.odyssey" -sdk iphoneos -scheme Odyssey -configuration Release -derivedDataPath build

    - name: Prepare Payload directory
      run: |
        ln -sf build/Build/Products/Release-iphoneos Payload
        rm -rf Payload/Odyssey.app/Frameworks

    - name: Create Odyssey IPA
      run: zip -r9 Odyssey.ipa Payload/Odyssey.app

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Odyssey IPA
        path: Odyssey.ipa
